config/routes.rb
Rhci2::Application.routes.draw do
  resources :blogs
  get 'fusor', :to => 'blogs#fusor'
  get 'angular', :to => 'blogs#angular'

  root :to => 'application#index'
  get 'ember-cli-live-reload.js', :to => 'application#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :name, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def index
    redirect_to fusor_path
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def fusor
  end

  def angular
  end


  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<div class="container">

<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>

app/views/blogs/edit.html.erb
<div class="container">

<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/index.html.erb
<div class="container">

<h1>Sample Rails ERB App</h1>

<div class="alert alert-info">
This is a live CRUD rails app. For demo purposes, this "represents" Foreman/Katello rails app. Sorry guys for the comparison :)
</div>

<table class="table table-bordered table-striped">
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.name %></td>
    <td><%= blog.url %></td>
    <td><%= link_to 'Show', blog %></td>
    <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
    <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blog', new_blog_path, :class => 'btn btn-default btn-small' %>

</div>

app/views/blogs/new.html.erb
<div class="container">

<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @blog.name %>
</p>

<p>
  <b>Url:</b>
  <%= @blog.url %>
</p>


<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fuser Demo</title>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <!-- Optional theme -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  <%= csrf_meta_tags %>

  <%= javascript_include_tag "application" %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Fusor Demo</title>
  <meta name="description" content="">
  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0"/>

  <link href="/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon" />

  <meta name="fusor-demo/config/environment" content="%7B%22modulePrefix%22%3A%22fusor-demo%22%2C%22environment%22%3A%22development%22%2C%22baseURL%22%3A%22/%22%2C%22locationType%22%3A%22hash%22%2C%22contentSecurityPolicyHeader%22%3A%22Disabled-Content-Security-Policy%22%2C%22EmberENV%22%3A%7B%22FEATURES%22%3A%7B%7D%7D%2C%22APP%22%3A%7B%22LOG_ACTIVE_GENERATION%22%3Atrue%2C%22LOG_TRANSITIONS%22%3Atrue%2C%22LOG_VIEW_LOOKUPS%22%3Atrue%7D%2C%22contentSecurityPolicy%22%3A%7B%22default-src%22%3A%22%27none%27%22%2C%22script-src%22%3A%22%27self%27%20%27unsafe-eval%27%22%2C%22font-src%22%3A%22%27self%27%22%2C%22connect-src%22%3A%22%27self%27%22%2C%22img-src%22%3A%22%27self%27%22%2C%22style-src%22%3A%22%27self%27%22%2C%22media-src%22%3A%22%27self%27%22%7D%2C%22exportApplicationGlobal%22%3Atrue%7D">

  <link rel="stylesheet" href="assets/vendor.css">
  <link rel="stylesheet" href="assets/fusor-demo.css">

</head>
<body>

    <div style="background-color:#ff4;text-align:center;font-weight:bold;">
        THIS IS A PROTOTYPE TO TEST THE FLOWS OF THE FUSOR PROJECT
    </div>

    <div class="container">
      <div>
          <%= link_to 'Fusor-Demo', fusor_path, :class => 'btn btn-default' %> &nbsp;
          <%= link_to 'Rails ERB', blogs_path, :class => 'btn btn-default' %> &nbsp;
          <%= link_to 'Angular App', angular_path, :class => 'btn btn-default' %>
      </div>
    </div>

    <%= yield %>

</body>
</html>